spring:
  application:
    name: infotech

  datasource:
    url: jdbc:mysql://localhost:3306/axenovo_db?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/template/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

axenovo:
  admin:
    username: admin@axenovo.com
    password: admin123
    name: Admin User

server:
  port: 9095 